### ISSUE TITLE
Upgrade of flask to 0.12.3 for CVE fix creates json encoder error

### ISSUE THREAD

**Issue by earcuri** [PaloAltoNetworks/SafeNetworking#84]
After upgrading Flask to 0.12.3 as per Github recommendation:

**Moderate severity**
The Pallets Project flask version Before 0.12.3 contains a CWE-20: Improper Input Validation vulnerability in flask t...

**requirements.txt update suggested:**
```
flask ~> 0.12.3
```

Doing the above totally horks the system and we get the below error.

AttributeError: 'Blueprint' object has no attribute 'json_encoder'

This is fixed in Flask 0.12.4 (theoretically)
